In [1]:
!conda install numpy -y

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 24.11.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/eli970616/opt/miniconda3/envs/house-price

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libblas-3.9.0              |25_osx64_openblas          16 KB  conda-forge
    libcblas-3.9.0             |25_osx64_openblas          15 KB  conda-forge
    libgfortran-5.0.0          |13_2_0_h97931a8_3         108 KB  conda-forge
    libgfortran5-13.2.0        |       h2873a65_3         1.5 MB  conda-forge
    liblapack-3.9.0            |25_osx64_openblas          15 KB  conda-forge
    libopenblas-0.3.28         |openmp_hbf64a52_1         5.9 MB  conda-forge
    llvm-openmp-19.1.4         |       ha54da

In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.1.3


In [ ]:
## 怎样创建数组

In [4]:
# 从列表或元组创建数组
arr = np.array([1, 2, 3, 4])
print(arr)  # 输出: [1 2 3 4]

[1 2 3 4]


In [5]:
zeros = np.zeros((2, 3))  # 创建 2 行 3 列的零矩阵
print(zeros)
# 输出:
# [[0. 0. 0.]
#  [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
ones = np.ones((3, 2))  # 创建 3 行 2 列的全一矩阵
print(ones)
# 输出:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
arange = np.arange(0, 10, 2)  # 从 0 开始，每次加 2，直到小于 10
print(arange)  # 输出: [0 2 4 6 8]


[0 2 4 6 8]


In [ ]:
## 数据计算

In [8]:
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))  # 输出: 10


10


In [9]:
print(np.mean(arr))  # 输出: 2.5


2.5


In [10]:
print(np.max(arr))  # 输出: 4
print(np.min(arr))  # 输出: 1


4
1


In [ ]:
## 访问数组元素：索引和切片

In [11]:
arr = np.array([10, 20, 30, 40])
print(arr[2])  # 输出: 30

30


In [12]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix[1, 1])  # 输出: 4 （第 1 行第 1 列的元素）

4


In [13]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # 输出: [20 30 40]


[20 30 40]


In [ ]:
## 矩阵计算

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)  # 矩阵乘法
print(result)
# 输出:
# [[19 22]
#  [43 50]]


[[19 22]
 [43 50]]


In [15]:
A = np.array([[1, 2], [3, 4], [5, 6]])
transposed = np.transpose(A)
print(transposed)
# 输出:
# [[1 3 5]
#  [2 4 6]]


[[1 3 5]
 [2 4 6]]


In [ ]:
## 数据形状操作

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # 转为 2 行 3 列
print(reshaped)
# 输出:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


In [17]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
flattened = matrix.ravel()
print(flattened)  # 输出: [1 2 3 4 5 6]


[1 2 3 4 5 6]
